export interface Interface {
    nombre:string;
    imagen:string;
    paginas:number;
    autor:string;
}

export const ListaLibros:Array<Interface>=
    [{  nombre:"Don Quijote de la Mancha",
        imagen:"libro1.webp",
        paginas:1345,
        autor:"Miguel de Cervantes Saavedra",
    },
    {   nombre:"Historia de dos ciudades",
        imagen:"libro2.jpg",
        paginas:512,
        autor:"Charles Dickens",
    },
    {   nombre:"El Señor de los Anillos",
        imagen:"libro3.webp",
        paginas:423,
        autor:"John Ronald Reuel Tolkien",
    },
    {   nombre:"Harry Potter y la piedra filosofal",
        imagen:"libro4.webp",
        paginas:288,
        autor:"Joanne Rowling",
    },
    {   nombre:"El principito",
        imagen:"libro5.jpg",
        paginas:111,
        autor:"Antoine de Saint-Exupéry",
    },
    {  nombre:"Don Quijote de la Mancha",
        imagen:"libro1.webp",
        paginas:1345,
        autor:"Miguel de Cervantes Saavedra",
    },
    {   nombre:"Historia de dos ciudades",
        imagen:"libro2.jpg",
        paginas:512,
        autor:"Charles Dickens",
    },
    {   nombre:"El Señor de los Anillos",
        imagen:"libro3.webp",
        paginas:423,
        autor:"John Ronald Reuel Tolkien",
    },
    {   nombre:"Harry Potter y la piedra filosofal",
        imagen:"libro4.webp",
        paginas:288,
        autor:"Joanne Rowling",
    },
    {   nombre:"El principito",
        imagen:"libro5.jpg",
        paginas:111,
        autor:"Antoine de Saint-Exupéry",
    }
]
